on:
  push: {tags: v*}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Determine npm cache directory
        id: npm-cache
        run: |
          echo "::set-output name=dir::$(npm config get cache)"

      - name: Restore npm cache
        uses: actions/cache@v1
        with:
          path: ${{ steps.npm-cache.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependecies
        run: npm install -D

      - name: Build action
        run: npm run build

      - name: Stage dist changes
        run: |
          git config --global user.email "roman@refactr.it"
          git config --global user.name $GITHUB_ACTOR
          git remote add github "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git"
          git add ./dist -f
          git commit -m "(dist) Update dist"
          git tag -d $(echo $GITHUB_REF | sed -e 's/^refs\/tags\///')
          git tag $(echo $GITHUB_REF | sed -e 's/^refs\/tags\///')
          git push github --tags -f
